# Generated by Django 5.2 on 2025-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0002_autores_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Boliviana'), ('BR', 'Brasileña'), ('CL', 'Chilena'), ('CO', 'Colombiana'), ('CR', 'Costarricense'), ('CU', 'Cubana'), ('DO', 'Dominicana'), ('EC', 'Ecuatoriana'), ('SV', 'Salvadoreña'), ('GT', 'Guatemalteca'), ('HN', 'Hondureña'), ('MX', 'Mexicana'), ('NI', 'Nicaragüense'), ('PA', 'Panameña'), ('PY', 'Paraguaya'), ('PE', 'Peruana'), ('PR', 'Puertorriqueña'), ('UY', 'Uruguaya'), ('VE', 'Venezolana'), ('ES', 'Española'), ('US', 'Estadounidense'), ('CA', 'Canadiense'), ('FR', 'Francesa'), ('DE', 'Alemana'), ('IT', 'Italiana'), ('PT', 'Portuguesa'), ('GB', 'Británica'), ('IE', 'Irlandesa'), ('CN', 'China'), ('JP', 'Japonesa'), ('KR', 'Coreana'), ('IN', 'India'), ('RU', 'Rusa'), ('AU', 'Australiana'), ('ZA', 'Sudafricana'), ('EG', 'Egipcia'), ('NG', 'Nigeriana'), ('KE', 'Keniata'), ('MA', 'Marroquí')], default='AR', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Autores',
        ),
    ]
