# Generated by Django 5.2 on 2025-04-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0003_autor_delete_autores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Autores',
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'ordering': ['id'], 'verbose_name': 'Autores', 'verbose_name_plural': 'Autores'},
        ),
    ]
