# Generated by Django 5.2 on 2025-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0005_alter_autores_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='nacionalidad',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Boliviana', 'Boliviana'), ('Brasileña', 'Brasileña'), ('Chilena', 'Chilena'), ('Colombiana', 'Colombiana'), ('Costarricense', 'Costarricense'), ('Cubana', 'Cubana'), ('Dominicana', 'Dominicana'), ('Ecuatoriana', 'Ecuatoriana'), ('Salvadoreña', 'Salvadoreña'), ('Guatemalteca', 'Guatemalteca'), ('Hondureña', 'Hondureña'), ('Mexicana', 'Mexicana'), ('Nicaragüense', 'Nicaragüense'), ('Panameña', 'Panameña'), ('Paraguaya', 'Paraguaya'), ('Peruana', 'Peruana'), ('Puertorriqueña', 'Puertorriqueña'), ('Uruguaya', 'Uruguaya'), ('Venezolana', 'Venezolana'), ('Española', 'Española'), ('Estadounidense', 'Estadounidense'), ('Canadiense', 'Canadiense'), ('Francesa', 'Francesa'), ('Alemana', 'Alemana'), ('Italiana', 'Italiana'), ('Portuguesa', 'Portuguesa'), ('Británica', 'Británica'), ('Irlandesa', 'Irlandesa'), ('China', 'China'), ('Japonesa', 'Japonesa'), ('Coreana', 'Coreana'), ('India', 'India'), ('Rusa', 'Rusa'), ('Australiana', 'Australiana'), ('Sudafricana', 'Sudafricana'), ('Egipcia', 'Egipcia'), ('Nigeriana', 'Nigeriana'), ('Keniata', 'Keniata'), ('Marroquí', 'Marroquí')], default='Argentina', max_length=20),
        ),
    ]
