# Generated by Django 5.2 on 2025-04-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0006_alter_autores_nacionalidad'),
        ('app_frases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frases',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases', to='app_autores.autores'),
        ),
    ]
